### ISSUE TITLE
We need to use the same format on the discount codes in billmate online.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#10]
See invoice number 420650 and 106730

106730 has percentage discount while 420650 has amount discount.

apilogsid: 14702 and 14695

**Comment by Boxedsolutions** [comment]
Hmm I think you spot a misstake there. Will check it up, but its odd that its not showing any discount article on 420650

**Comment by Boxedsolutions** [comment]
I guess this issue was with encoding as the values was sent to Billmate but the title becomed null due to encoding. Should be solved now

**Comment by joakim-combain** [comment]
I still can't use discount codes it seems so I cannot confirm this at the moment.

**Comment by Boxedsolutions** [comment]
I dont get why you cant, but I post a image to verify that i understand you right with discount codes
![skarmklipp 2015-04-01 11 43 05](https://cloud.githubusercontent.com/assets/8977650/6938537/6ad66590-d864-11e4-9268-0e6027d0250c.png)

**Comment by joakim-combain** [comment]
I think the issue is with Invoice and Part pay only. I tried in firefox as well and it doesn't work.

**Comment by joakim-combain** [comment]
Also you have to activate the address popup it seems.

**Comment by Boxedsolutions** [comment]
You could test invoice now and se if it works. I updated the logics to use Ajax for validation so that the coupon code should be persisted, I havent yet fixed it for partpayment.

**Comment by joakim-combain** [comment]
Looks like that fixed the issue. Let me know when it's fixed for part payment and I'll test both.

**Comment by Boxedsolutions** [comment]
It should be now. It was just before the commit i didnt have uploaded the partpayment part.

**Comment by joakim-combain** [comment]
Is the discount text ok or should we change it? I think it looks kind of messy tbh.

![oscommerce discount](https://cloud.githubusercontent.com/assets/10434920/6959777/91cc6808-d91c-11e4-87a7-e6ca2cd6845e.png)

**Comment by Boxedsolutions** [comment]
We could style up the Moms part. The rest is from the plugin.

**Comment by andyjohansson** [comment]
Yes, and also translate the first part:
Svenska: Rabatt kupong - XXXX - 25% moms
Engelska: Discount coupon - XXX - 25% VAT

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-02 10 02 13](https://cloud.githubusercontent.com/assets/8977650/6960068/60ea3b18-d91f-11e4-9477-97105eb13b66.png)
Its also possible for customer to use language file to translate. The only thing i have done is added the VAT part

**Comment by andyjohansson** [comment]
Now I don´t quite follow, where is this setting, general in osCommerce or in pur plugin?

**Comment by Boxedsolutions** [comment]
This setting is in the coupon module. I think it may be very strange if we modify to much

**Comment by andyjohansson** [comment]
Yes, that´s true. But fix the formatting of the VAT then 😉

**Comment by andyjohansson** [comment]
Yes
