### ISSUE TITLE
I chose UK as country for my address. Now I can choose Bank to pay with.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#15]
Seems to be issues with country restrictions. We should use same restrictions here as in woocommerce.

**Comment by Boxedsolutions** [comment]
Should be fixed now. Only Sweden is now allowed with bank

**Comment by joakim-combain** [comment]
Seems like this is still an issue. I tried in two different browsers and it seems like I still can choose my UK address and buy with bank.

**Comment by Boxedsolutions** [comment]
Should be solved now

**Comment by joakim-combain** [comment]
This seems to work. I'm still able to add UK or choose Norway for Invoice since in backend we still have these settings. Should we limit the user here or what did we decide?

**Comment by Boxedsolutions** [comment]
The specification says: 
Country code for the country where purchase is made (normally store location) according to ISO 3166-1 alpha-2, e.g. SE, DK, NO, GB

What should it be then? It might need to be clarified in the spec ;)

**Comment by andyjohansson** [comment]
Clarified over the phone.

**Comment by Boxedsolutions** [comment]
Removed countries that not should be working

**Comment by Boxedsolutions** [comment]
It should work now
